# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Weather API configuration
weather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast
    key: YOUR_API_KEY_HERE
    units: "metric"